baseurl = "https://www.stephenmcgruer.com/"
languageCode = "en-us"
title = "Stephen McGruer"
theme = "hugo-ink"
paginate = 5

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    subtitle = "Cookies. Coding. Cumbersome Writing."
    mode = "auto"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/stephenmcgruer"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/stephen-mcgruer/"

[taxonomies]
   tag = "tags"
